import type { ColumnType } from "kysely";
export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;
export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type Configuration = {
    id: Generated<number>;
    plexServerUrl: string | null;
    plexToken: string | null;
    jellyfinServerUrl: string | null;
    jellyfinApiKey: string | null;
    jellyfinUserId: string | null;
    tmdbApiKey: string | null;
    fanartApiKey: string | null;
    removeOverlays: Generated<number>;
    thePosterDbEmail: string | null;
    thePosterDbPassword: string | null;
};
export type JellyfinEpisode = {
    id: Generated<number>;
    ratingKey: string;
    parentRatingKey: string;
    title: string;
    index: number | null;
    parentIndex: number | null;
    year: number | null;
    summary: string | null;
    thumbUrl: string | null;
    artUrl: string | null;
    duration: number | null;
    guid: string | null;
    importedAt: Generated<string>;
};
export type JellyfinMovie = {
    id: Generated<number>;
    ratingKey: string;
    libraryKey: string;
    title: string;
    year: number | null;
    summary: string | null;
    thumbUrl: string | null;
    artUrl: string | null;
    duration: number | null;
    rating: number | null;
    contentRating: string | null;
    guid: string | null;
    importedAt: Generated<string>;
};
export type JellyfinSeason = {
    id: Generated<number>;
    ratingKey: string;
    parentRatingKey: string;
    type: string;
    title: string;
    parentKey: string;
    parentTitle: string | null;
    summary: string | null;
    index: number | null;
    year: number | null;
    thumbUrl: string | null;
    artUrl: string | null;
    parentThumb: string | null;
    parentTheme: string | null;
};
export type JellyfinShow = {
    id: Generated<number>;
    ratingKey: string;
    libraryKey: string;
    title: string;
    year: number | null;
    summary: string | null;
    thumbUrl: string | null;
    artUrl: string | null;
    duration: number | null;
    rating: number | null;
    contentRating: string | null;
    guid: string | null;
    importedAt: Generated<string>;
};
export type PlexEpisode = {
    id: Generated<number>;
    ratingKey: string;
    parentRatingKey: string;
    title: string;
    index: number | null;
    parentIndex: number | null;
    year: number | null;
    summary: string | null;
    thumbUrl: string | null;
    artUrl: string | null;
    duration: number | null;
    guid: string | null;
    importedAt: Generated<string>;
};
export type PlexMovie = {
    id: Generated<number>;
    ratingKey: string;
    libraryKey: string;
    title: string;
    year: number | null;
    summary: string | null;
    thumbUrl: string | null;
    artUrl: string | null;
    duration: number | null;
    rating: number | null;
    contentRating: string | null;
    guid: string | null;
    importedAt: Generated<string>;
};
export type PlexSeason = {
    id: Generated<number>;
    ratingKey: string;
    parentRatingKey: string;
    type: string;
    title: string;
    parentKey: string;
    parentTitle: string | null;
    summary: string | null;
    index: number | null;
    year: number | null;
    thumbUrl: string | null;
    artUrl: string | null;
    parentThumb: string | null;
    parentTheme: string | null;
};
export type PlexShow = {
    id: Generated<number>;
    ratingKey: string;
    libraryKey: string;
    title: string;
    year: number | null;
    summary: string | null;
    thumbUrl: string | null;
    artUrl: string | null;
    duration: number | null;
    rating: number | null;
    contentRating: string | null;
    guid: string | null;
    importedAt: Generated<string>;
};
export type DB = {
    Configuration: Configuration;
    JellyfinEpisode: JellyfinEpisode;
    JellyfinMovie: JellyfinMovie;
    JellyfinSeason: JellyfinSeason;
    JellyfinShow: JellyfinShow;
    PlexEpisode: PlexEpisode;
    PlexMovie: PlexMovie;
    PlexSeason: PlexSeason;
    PlexShow: PlexShow;
};
